// Command sdkgen writes the TypeScript wire types of @keel/sdk from the Go
// types, so the browser side never holds a hand-kept mirror of them.
//
//	go -C tools/sdkgen run . -root ../.. -out ../../sdk-ts/src/generated/wire.ts
//
// It runs from internal/transport's go:generate directive (make generate) and
// make check-sdk fails on a non-empty diff of its output.
//
// A module of its own, so that the generator's dependencies (guts, its
// TypeScript engine, golang.org/x/tools) never enter the module graph keeld is
// built from. It loads KEEL's packages by changing into the repository root
// first: `go list` then resolves them against KEEL's own go.mod, and this
// module needs nothing of KEEL's but its source.
//
// coder/guts rather than tygo: guts reads the types through go/types, so a
// typed const block becomes a union of string literals whatever its names;
// tygo recognises an enum only when every constant carries the full type name
// as a prefix (CommandTypeGoto), which KEEL's idiomatic names do not.
package main

import (
	"flag"
	"fmt"
	"log"
	"os"
	"path/filepath"

	"github.com/coder/guts"
	"github.com/coder/guts/bindings"
	"github.com/coder/guts/config"
)

const keel = "github.com/dsanchez31/keel/internal/"

// generated are the packages whose types are on the wire, but for those
// excluded below: the domain model, the transport's views, bodies and frames,
// and the Plan IR with its diagnostics. Generated in full rather than
// referenced, so their typed const blocks (FrameType, Gate) become unions:
// a referenced package contributes its types but not its constants.
var generated = []string{"./internal/domain", "./internal/transport", "./internal/planir"}

// referenced contribute only the types a generated package reaches: the
// compilation outcome, the allocator's assignments, a doctrine pack's
// document.
var referenced = []string{"./internal/planner", "./internal/assign", "./internal/doctrine"}

// excluded are the exported types of the generated packages that never
// cross the wire: the service interface, the hub and its options, the
// handler's options, the hub's internal message; the world file and the
// validator's input and result.
var excluded = []string{
	keel + "transport.Service",
	keel + "transport.Options",
	keel + "transport.Hub",
	keel + "transport.HubOptions",
	keel + "transport.Message",
	keel + "planir.World",
	keel + "planir.AreaSpec",
	keel + "planir.FleetVector",
	keel + "planir.Input",
	keel + "planir.Result",
}

func main() {
	root := flag.String("root", ".", "the KEEL repository root")
	out := flag.String("out", "", "the TypeScript file to write")
	flag.Parse()
	if *out == "" {
		log.Fatal("sdkgen: -out is required")
	}
	target, err := filepath.Abs(*out)
	if err != nil {
		log.Fatal(err)
	}
	if err := os.Chdir(*root); err != nil {
		log.Fatal(err)
	}

	src, err := generate()
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile(target, []byte(src), 0o644); err != nil {
		log.Fatal(err)
	}
}

func generate() (string, error) {
	p, err := guts.NewGolangParser()
	if err != nil {
		return "", err
	}
	p.PreserveComments()
	for _, dir := range generated {
		if err := p.IncludeGenerate(dir); err != nil {
			return "", err
		}
	}
	for _, dir := range referenced {
		if err := p.IncludeReference(dir, ""); err != nil {
			return "", err
		}
	}
	if err := p.ExcludeCustom(excluded...); err != nil {
		return "", err
	}
	// A frame's data is typed per frame type by the SDK (stream.ts); on the
	// Go side it is raw JSON, read (json.RawMessage) or written already
	// canonical (eventlog.RawJSON, a replay window's frames).
	p.IncludeCustomDeclaration(map[string]guts.TypeOverride{
		"encoding/json.RawMessage":                             config.OverrideLiteral(bindings.KeywordUnknown),
		"github.com/dsanchez31/keel/internal/eventlog.RawJSON": config.OverrideLiteral(bindings.KeywordUnknown),
	})

	ts, err := p.ToTypescript()
	if err != nil {
		return "", err
	}
	ts.ApplyMutations(
		// A typed const block is a union of its string literals.
		config.EnumAsTypes,
		// The canonical encoding omits an absent optional and never emits
		// null (spec section 9), so an omitempty field is `field?: T`.
		config.SimplifyOmitEmpty,
		config.ExportTypes,
		// Wire data is read, never written back.
		config.ReadOnly,
	)
	body, err := ts.Serialize()
	if err != nil {
		return "", err
	}
	return fmt.Sprintf("// Generated by tools/sdkgen from the Go types of internal/domain,\n// internal/transport and internal/planir: change the Go type, then run\n// make generate.\n\n%s", body), nil
}
